"""init schema

Revision ID: 0fd4a18b396b
Revises: 0001_init_schema
Create Date: 2026-02-22 18:24:22.455413

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fd4a18b396b'
down_revision: Union[str, None] = '0001_init_schema'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_unit_price_history_unit_id_captured_at_desc'), table_name='unit_price_history')
    op.create_index('ix_unit_price_history_unit_id_captured_at_desc', 'unit_price_history', ['unit_id', sa.literal_column('captured_at DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_unit_price_history_unit_id_captured_at_desc', table_name='unit_price_history')
    op.create_index(op.f('ix_unit_price_history_unit_id_captured_at_desc'), 'unit_price_history', ['unit_id', 'captured_at'], unique=False)
    # ### end Alembic commands ###

